baseURL = "http://alexander.yarkosky.xyz/"
languageCode = "en-us"
title = "Alex Yarkosky"
theme = "hyde-hyde"
[params.description]
	description = "The hub to find out all about me, what I have done, and what I am doing."
[params.social]
	github = "Alex-Yarkosky"
	linkedin = "alexander-yarkosky"
	stackoverflow = "10458183"

